<a href="https://colab.research.google.com/github/WBLauer/COMSC240---linkedRP/blob/main/pandas2_Will_Lauer_Lab_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ⚠ **Do not delete or recreate the provided cells** (instructions and answer cells). Write your answers ONLY inside the provided answer cells. If a provided cell is deleted or replaced, your work in that part **may be excluded from grading**. Deleted a cell by accident? Open a FRESH copy of the template from the assignment link and paste your work into the matching answer cells, or use **File → Revision history** to restore. **Save and pin a revision at the end of each section.**

# Pandas Data Analysis

**What you build:** you explore three real datasets with pandas — reading them in, inspecting their shape, and asking questions of the data.

### How this notebook works
Each section runs in the same rhythm:
1. A short description of the dataset, and a **setup cell you just run**.
2. **Problems** — each one has an empty answer cell marked `# YOUR CODE HERE`. Write your answer there.
3. A **Reflection** question at the end of the section.
4. **`File` → `Save and pin revision`**, named `Section N`.

### The three datasets
| Section | Dataset | What it holds |
|---|---|---|
| 1 – 4 | **Iris** | 150 iris flowers, 4 measurements each, 3 species |
| 5 | **California Housing** | 20,640 census block groups, 8 features + median house value |
| 6 – 7 | **Linnerud** | 20 men at a fitness center, 3 exercise counts each |

### Reference
[10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html) — the same tutorial as Lab 1.

## Section 1 — Reading Datasets

**Goal of this section:** load a dataset that ships with scikit-learn and turn it into a `DataFrame`.

#### The Iris dataset
The **Iris dataset** is one of the most-used datasets in machine learning. It measures **150 iris flowers** — 50 of each of 3 species.

| | |
|---|---|
| Rows (flowers) | 150 |
| Features | 4 numeric measurements, in centimetres |
| Species | `setosa`, `versicolor`, `virginica` (50 each) |

**The 4 measurements:** `sepal length (cm)`, `sepal width (cm)`, `petal length (cm)`, `petal width (cm)`.

A **petal** is an inner flower leaf; a **sepal** is the outer leaf that protects the bud — here they are on all three species:

![iris petal and sepal](https://raw.githubusercontent.com/DVC-COMSC/PythonPandas/main/png/iris.png)

#### How scikit-learn hands you the data
`datasets.load_iris()` returns an object, **not** a `DataFrame`:

| Attribute | What it is |
|---|---|
| `iris.data` | a 150 × 4 NumPy array — the measurements |
| `iris.target` | 150 numbers: `0`, `1`, or `2` — which species each flower is |
| `iris.feature_names` | the 4 column names |
| `iris.target_names` | `['setosa', 'versicolor', 'virginica']` — what `0/1/2` mean |

So building the `DataFrame` takes two steps: the measurements become the columns, then the species is added as one more column. **Run the next cell** — every problem in Sections 1–4 uses the `iris_df` it creates.

In [ ]:
import pandas as pd
from sklearn import datasets

# Load the dataset (measurements + labels + documentation)
iris = datasets.load_iris()

# The 4 measurements become the columns
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

# Add the species as a 5th column. iris.target is 0/1/2; target_names turns
# those numbers into 'setosa' / 'versicolor' / 'virginica'.
iris_df['target'] = iris.target_names[iris.target]

iris_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

You should see a table of **150 rows × 5 columns** — the 4 measurements plus `target`. The row labels `0..149` on the left are the index; pandas made them for you.

Note the column names include the units: the column is `sepal length (cm)`, **not** `sepal_length`. You must type them exactly, parentheses and all.

<!-- @anchor:S1R type=explain -->
### Reflection — Section 1: Reading Datasets
In a sentence or two — **what can you now do that you could not before?**

- `iris.data` was a plain NumPy array. What did turning it into a `DataFrame` give you?
- Why did `target` need `iris.target_names[iris.target]` instead of just `iris.target`?

<!-- @answer:S1R -->
*(write your takeaway here — do not delete this cell)* --- even though we didnt do much in this section, It was nice to see how to proporly load in data and get it ready for use with extra information to make it easy for us access specific parts.Turning it to a DataFrame allows us to pull specific elements from the data by using the syntax we practiced in lab 1. Now we can use pd to get more info. Adding the extra line gave names to those numbers that were just sitting in the 5th column now they actually have names that can give even more insight to our data.

> **Save and pin a revision now** — `File` → `Save and pin revision` — and name it **`Section 1`**. Do not delete the cells above.

## Section 2 — Exploring Datasets

**Goal of this section:** get a first look at a table you have never seen — its first rows, its column types, and the range of its values.

All problems use `iris_df` from Section 1.

<!-- @anchor:P2.1 type=code -->
#### Problem 2.1  `[code]`

Display the **first 5 rows** of `iris_df`.

**Expected result:** a table of **5 rows × 5 columns**, index `0` to `4`. Every row's `target` is `setosa`, and the first row's `sepal length (cm)` is `5.1`.

*Hint: one method shows the top of a table. Its default is 5 rows.*

In [ ]:
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

<!-- @anchor:P2.2 type=code -->
#### Problem 2.2  `[code]`

Now display the **first 10 rows**.

**Expected result:** the same table as 2.1 but with index `0` to `9` — **10 rows × 5 columns**.

*Hint: the same method as 2.1. It takes one argument.*

In [ ]:
# @answer:P2.2
# YOUR CODE HERE  (do not delete this cell)

iris_df.head(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa

<!-- @anchor:P2.3 type=code -->
#### Problem 2.3  `[code]`

Show the **data type of every column**.

**Expected output**
```
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                object
dtype: object
```

Notice the answer to "what type is `target`?" is `object` — that is how pandas labels a column of **text**, while the four measurements are `float64` (decimal numbers).

*Hint: it is an attribute, not a method — no parentheses.*

In [ ]:

iris_df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                object
dtype: object

<!-- @anchor:P2.4 type=code -->
#### Problem 2.4  `[code]`

Print the **largest** and the **smallest** `sepal length (cm)` — two values, each on its own line.

**Expected output**
```
7.9
4.3
```

*Hint: select the column first, then apply a method to it. Wrap each in `print()` so you get plain numbers on separate lines.*

In [ ]:
# @answer:P2.4
# YOUR CODE HERE  (do not delete this cell)

print(iris_df['sepal length (cm)'].max())
print(iris_df['sepal length (cm)'].min())

7.9
4.3

---
#### Try Problems 2.5 – 2.7 on your own.
---

<!-- @anchor:P2.5 type=code -->
#### Problem 2.5  `[code]`

Print the **average `petal length (cm)`** and the **average `petal width (cm)`** — two values, each on its own line.

**Expected output**
```
3.7580000000000005
1.1993333333333336
```

*Those long tails are normal — that is how binary floating point stores 3.758. Do not round.*

In [ ]:
# @answer:P2.5
# YOUR CODE HERE  (do not delete this cell)
print(iris_df['petal length (cm)'].mean())
print(iris_df['petal width (cm)'].mean())

3.7580000000000005
1.1993333333333336

<!-- @anchor:P2.6 type=code -->
#### Problem 2.6  `[code]`

Print the **largest** and the **smallest** `petal width (cm)` — two values, each on its own line.

**Expected output**
```
2.5
0.1
```

*Same shape as 2.4, different column.*

In [ ]:
# @answer:P2.6
# YOUR CODE HERE  (do not delete this cell)

print(iris_df['petal width (cm)'].max())
print(iris_df['petal width (cm)'].min())

2.5
0.1

<!-- @anchor:P2.7 type=code -->
#### Problem 2.7  `[code]`  —  challenge

In 2.1 you used a method that shows the **first** rows of a table. **What would show the LAST rows?** Work it out and display the last 5 rows of `iris_df`.

**Expected result:** **5 rows × 5 columns**, index `145` to `149`. Every row's `target` is `virginica`.

*The name is the opposite of the one you used in 2.1 — guess it, then try it.*

In [ ]:
# @answer:P2.7
# YOUR CODE HERE  (do not delete this cell)

iris_df.tail()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

<!-- @anchor:S2R type=explain -->
### Reflection — Section 2: Exploring Datasets
In a sentence or two — **what can you now do that you could not before?**

- You have a table of 150 rows you have never seen. Which of these methods do you run first, and what does each one tell you?
- In 2.3, why is `target` typed `object` while the measurements are `float64`?

<!-- @answer:S2R -->
*(write your takeaway here — do not delete this cell)* --- In this section it was nice rememebering what I did in the previous lab since there was such a direct corrolation. If you want some quick insight to your data, a good start would be to use head() and tail() of your data and an even better method is to use .describe() since that will give you a 5 number summary for your data. I am pretty sure that the target is labled as an object since that is the classification we put on each kind of flower since a certain flower has been named and put into a group. it is not an object rather than a number or a float.

> **Save and pin a revision now** — `File` → `Save and pin revision` — and name it **`Section 2`**. Do not delete the cells above.

## Section 3 — DataFrame Attributes

**Goal of this section:** ask a `DataFrame` about **itself** — how big it is, what its columns are called, what is in a given row.

These are **attributes**, not methods: `iris_df.shape`, not `iris_df.shape()`. An attribute is a stored fact about the object, so it needs no parentheses. All problems use `iris_df`.

<!-- @anchor:P3.1 type=code -->
#### Problem 3.1  `[code]`

Show the **number of rows and columns** in `iris_df` — as a single result, not two separate numbers.

**Expected output**
```
(150, 5)
```

That pair reads `(rows, columns)`.

*Hint: one attribute gives both at once.*

In [ ]:
# @answer:P3.1
# YOUR CODE HERE  (do not delete this cell)
iris_df.shape

(150, 5)

<!-- @anchor:P3.2 type=code -->
#### Problem 3.2  `[code]`

Show the **total number of data elements** in `iris_df` — its *size*, meaning every cell in the table counted.

**Expected output**
```
750
```

*Check it against 3.1: 150 × 5 = 750. One attribute reports it directly.*

In [ ]:
# @answer:P3.2
# YOUR CODE HERE  (do not delete this cell)

print(iris_df.size)
print(150 * 5)

750
750

<!-- @anchor:P3.3 type=code -->
#### Problem 3.3  `[code]`

Show the **name of the first column**.

**Expected output**
```
'sepal length (cm)'
```

*Hint: one attribute gives all the column names as a list-like object — then index into it. Python counts from 0.*

In [ ]:
# @answer:P3.3
# YOUR CODE HERE  (do not delete this cell)

print(iris_df.columns[0])

sepal length (cm)

<!-- @anchor:P3.4 type=code -->
#### Problem 3.4  `[code]`

Display all the values in the **7th row**.

**Expected output**
```
sepal length (cm)       4.6
sepal width (cm)        3.4
petal length (cm)       1.4
petal width (cm)        0.3
target               setosa
Name: 6, dtype: object
```

**Careful — Python counts from 0, so the 7th row has index `6`.** Note `Name: 6` in the output confirms which row you got.

*Hint: `.iloc[]` selects by POSITION (Lab 1, Section 2.3).*

In [ ]:
# @answer:P3.4
# YOUR CODE HERE  (do not delete this cell)
iris_df.iloc[6]

sepal length (cm)       4.6
sepal width (cm)        3.4
petal length (cm)       1.4
petal width (cm)        0.3
target               setosa
Name: 6, dtype: object

---
#### Try Problems 3.5 – 3.6 on your own.
---

<!-- @anchor:P3.5 type=code -->
#### Problem 3.5  `[code]`

Show the **names of all the columns**.

**Expected output**
```
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')
```

*You already used this attribute inside 3.3 — here just show the whole thing.*

In [ ]:
# @answer:P3.5
# YOUR CODE HERE  (do not delete this cell)

print(iris_df.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

<!-- @anchor:P3.6 type=code -->
#### Problem 3.6  `[code]`

Show the **name of the third column**.

**Expected output**
```
'petal length (cm)'
```

*Same as 3.3 — mind the 0-based counting.*

In [ ]:
# @answer:P3.6
# YOUR CODE HERE  (do not delete this cell)

print(iris_df.columns[2])

petal length (cm)

<!-- @anchor:S3R type=explain -->
### Reflection — Section 3: DataFrame Attributes
In a sentence or two — **what can you now do that you could not before?**

- `shape`, `size`, `columns` take no parentheses, but `head()` does. What is the difference between an attribute and a method?
- The 7th row had index `6`. Where else in this section did 0-based counting nearly trip you up?

<!-- @answer:S3R -->
*(write your takeaway here — do not delete this cell)*. --- This section was helpful for making sure i know how to find individual points of data from my dataframe. For example things like column names and all values in column 7. Shape size and columns are attributes. Attributes are stats about the data itseld as a whole like the rows,columns or column names,  where as .head() is method since it is getting info from the data set like specific points.

> **Save and pin a revision now** — `File` → `Save and pin revision` — and name it **`Section 3`**. Do not delete the cells above.

## Section 4 — Most Common and Unique Values

**Goal of this section:** stop looking at rows and start **counting** — which values appear, and how often.

Two methods carry this section:

| Method | Answers |
|---|---|
| `.value_counts()` | "how many times does each value appear?" — sorted, most common first |
| `.unique()` | "which distinct values exist?" |

All problems use `iris_df`.

<!-- @anchor:P4.1 type=code -->
#### Problem 4.1  `[code]`

Which **`sepal width (cm)` value appears exactly 9 times** in the dataset?

Display the counts for that column, then read the answer off the output.

**Expected result:** a list of each sepal width and its count. Find the row whose count is `9` — the value is **`2.7`**.

*Hint: `.value_counts()` on the column. The value is the left-hand label, the count is the number beside it.*

In [ ]:
# @answer:P4.1
# YOUR CODE HERE  (do not delete this cell)

iris_df['sepal width (cm)'].value_counts()

sepal width (cm)
3.0    26
2.8    14
3.2    13
3.4    12
3.1    11
2.9    10
2.7     9
2.5     8
3.3     6
3.5     6
3.8     6
2.6     5
3.6     4
2.3     4
3.7     3
2.2     3
2.4     3
3.9     2
4.4     1
4.2     1
4.1     1
4.0     1
2.0     1
Name: count, dtype: int64

<!-- @anchor:P4.2 type=code -->
#### Problem 4.2  `[code]`

Show **which iris species are in the dataset** — the distinct values of `target`, with no repeats.

**Expected output**
```
array(['setosa', 'versicolor', 'virginica'], dtype=object)
```

*Hint: this is the `.unique()` method, not `.value_counts()` — you want WHICH, not HOW MANY.*

In [ ]:
# @answer:P4.2
# YOUR CODE HERE  (do not delete this cell)

iris_df['target'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

---
#### Try Problems 4.3 – 4.5 on your own.
---

<!-- @anchor:P4.3 type=code -->
#### Problem 4.3  `[code]`

Print the **most common `petal length (cm)`** — the single value that appears more often than any other.

**Expected output**
```
1.4
```

*Hint: `.value_counts()` returns its results already sorted, most common FIRST. So you want the first label of that result — `.index[0]` gives it. (Careful: `.max()` would give you the biggest COUNT, not the value.)*

In [ ]:
# @answer:P4.3
# YOUR CODE HERE  (do not delete this cell)

iris_df['petal length (cm)'].value_counts().index[0]

np.float64(1.4)

<!-- @anchor:P4.4 type=code -->
#### Problem 4.4  `[code]`

Print **how many distinct `petal length (cm)` values** there are.

**Expected output**
```
43
```

*So 150 flowers share only 43 different petal lengths. Hint: count what `.unique()` returns — or use the one method that does both steps.*

In [ ]:
# @answer:P4.4
# YOUR CODE HERE  (do not delete this cell)

iris_df['petal length (cm)'].unique().size

43

<!-- @anchor:P4.5 type=code -->
#### Problem 4.5  `[code]`

Show **how many flowers of each species** are in the dataset.

**Expected output**
```
target
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64
```

*A perfectly balanced dataset — 50 of each. Hint: this is HOW MANY, so it is the other method from 4.2.*

In [ ]:
# @answer:P4.5
# YOUR CODE HERE  (do not delete this cell)

iris_df['target'].value_counts()

target
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

<!-- @anchor:S4R type=explain -->
### Reflection — Section 4: Most Common and Unique Values
In a sentence or two — **what can you now do that you could not before?**

- `.value_counts()` and `.unique()` both look at a column. When do you reach for each?
- In 4.3, why does `.max()` on a `.value_counts()` result give the wrong answer?

<!-- @answer:S4R -->
*(write your takeaway here — do not delete this cell)* --- For me, this was very similar to section 3 however this was more indepth and you did more calculations of these different values from those specific numbers we pulled in section 3. .value_counts is how many times a value repeats itseld in a column where as unique as it sounds finds all the unique values in a column. Because in 4,3 we are looking for the number that shows up the most not the number that is the greatest those two are not the same.

> **Save and pin a revision now** — `File` → `Save and pin revision` — and name it **`Section 4`**. Do not delete the cells above.

## Section 5 — Check Your Understanding

**Goal of this section:** you have done Sections 2–4 on a 150-row table. Now do the same moves on a **20,640-row** table you have never seen — with no worked examples. Everything you need, you already used.

#### The California Housing dataset
From the 1990 U.S. Census. One row = one **census block group** (the smallest area the Census publishes, typically 600–3,000 people).

| Column | Meaning |
|---|---|
| `MedInc` | median income in the block group (in $100,000s) |
| `HouseAge` | median house age in the block group |
| `AveRooms` | average rooms per household |
| `AveBedrms` | average bedrooms per household |
| `Population` | block group population |
| `AveOccup` | average household members |
| `Latitude` / `Longitude` | where the block group is |
| `MedHouseVal` | **median house value** (in $100,000s) — the value being predicted |

**Run the setup cell below before answering.** It downloads the data the first time, so give it a few seconds.

In [ ]:
# Load the dataset (downloads on first run)
cali_housing = datasets.fetch_california_housing()

# Features become the columns
ca_df = pd.DataFrame(data=cali_housing.data, columns=cali_housing.feature_names)

# Add the target (median house value) as one more column
ca_df[cali_housing.target_names[0]] = cali_housing.target

ca_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

<!-- @anchor:P5.1 type=code -->
#### Problem 5.1  `[code]`

Display the **first 5 rows** of `ca_df`.

**Expected result:** **5 rows × 9 columns**, index `0` to `4`. The first row's `MedInc` is `8.3252` and its `MedHouseVal` is `4.526`.

*(That first block group: median income $832,520 — Census-coded in $100,000s — and a median house value of $452,600.)*

In [ ]:
# @answer:P5.1
# YOUR CODE HERE  (do not delete this cell)

ca_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

<!-- @anchor:P5.2 type=code -->
#### Problem 5.2  `[code]`

Show the **column names**, and how many there are.

**Expected result:** the 9 names — `MedInc`, `HouseAge`, `AveRooms`, `AveBedrms`, `Population`, `AveOccup`, `Latitude`, `Longitude`, `MedHouseVal`.

*Hint: the same attribute you used in 3.5. To get the count, `len()` around it.*

In [ ]:
# @answer:P5.2
# YOUR CODE HERE  (do not delete this cell)

print(ca_df.columns)
print(len(ca_df.columns))

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude', 'MedHouseVal'],
      dtype='object')
9

<!-- @anchor:P5.3 type=code -->
#### Problem 5.3  `[code]`

Show the **data type of each column**.

**Expected output**
```
MedInc         float64
HouseAge       float64
AveRooms       float64
AveBedrms      float64
Population     float64
AveOccup       float64
Latitude       float64
Longitude      float64
MedHouseVal    float64
dtype: object
```

*Unlike iris, every column here is numeric — there is no text column. Same attribute as 2.3.*

In [ ]:
# @answer:P5.3
# YOUR CODE HERE  (do not delete this cell)

ca_df.dtypes

MedInc         float64
HouseAge       float64
AveRooms       float64
AveBedrms      float64
Population     float64
AveOccup       float64
Latitude       float64
Longitude      float64
MedHouseVal    float64
dtype: object

<!-- @anchor:P5.4 type=code -->
#### Problem 5.4  `[code]`

Print the **number of rows** in `ca_df` (how many block groups were recorded).

**Expected output**
```
20640
```

*Hint: `len()` on the DataFrame gives rows directly. `.shape` would also tell you — it is the first of the pair.*

In [ ]:
# @answer:P5.4
# YOUR CODE HERE  (do not delete this cell)

len(ca_df)

20640

<!-- @anchor:P5.5 type=code -->
#### Problem 5.5  `[code]`

Display the values in the **15th row**.

**Expected output**
```
MedInc            1.916700
HouseAge         52.000000
AveRooms          4.262903
AveBedrms         1.009677
Population     1212.000000
AveOccup          1.954839
Latitude         37.850000
Longitude      -122.260000
MedHouseVal       1.592000
Name: 14, dtype: float64
```

**The 15th row has index `14`** — the `Name: 14` in the output confirms it. Same move as 3.4.

In [ ]:
# @answer:P5.5
# YOUR CODE HERE  (do not delete this cell)

ca_df.iloc[14]

MedInc            1.916700
HouseAge         52.000000
AveRooms          4.262903
AveBedrms         1.009677
Population     1212.000000
AveOccup          1.954839
Latitude         37.850000
Longitude      -122.260000
MedHouseVal       1.592000
Name: 14, dtype: float64

<!-- @anchor:P5.6 type=code -->
#### Problem 5.6  `[code]`

Print **how many distinct `Longitude` values** there are.

**Expected output**
```
844
```

*So 20,640 block groups sit on only 844 distinct longitudes. Same move as 4.4.*

In [ ]:
# @answer:P5.6
# YOUR CODE HERE  (do not delete this cell)

ca_df['Longitude'].unique().size

844

<!-- @anchor:P5.7 type=code -->
#### Problem 5.7  `[code]`

Print the **most common `HouseAge`**.

**Expected output**
```
52.0
```

*52 is the dataset's ceiling — every block group older than 52 was recorded as 52, so it piles up. Same move as 4.3.*

In [ ]:
# @answer:P5.7
# YOUR CODE HERE  (do not delete this cell)

print(ca_df['HouseAge'].value_counts().index[0])

52.0

<!-- @anchor:S5R type=explain -->
### Reflection — Section 5: Check Your Understanding
In a sentence or two — **what can you now do that you could not before?**

- This section had no worked examples and a table 137× bigger than iris, yet the same methods worked. What does that tell you about how pandas scales?
- Which problem did you have to look back at an earlier section for, and which one?

<!-- @answer:S5R -->
*(write your takeaway here — do not delete this cell)* --- This is just a redo of the second section with the iris data set. Even though this data set is so much larger the same methods still work since pandas does insights on the entire data set no matter the size so things like .value_counts still counts all the similar values and head() still works since yes its larger however it still has a first 5 rows. I had to look at the earlier section for the second to last problem  5.6 since i forgot that size is an attribute rather than a method and I kept getting an error for writing .size() at the end.

> **Save and pin a revision now** — `File` → `Save and pin revision` — and name it **`Section 5`**. Do not delete the cells above.

## Section 6 — Working with Rows and Columns

**Goal of this section:** select exactly the rows and columns you want — one value, one row, one column, a range, or rows that meet a condition.

#### The Linnerud dataset
20 middle-aged men at a fitness center, three exercises each:

| Column | Meaning |
|---|---|
| `Chins` | chin-ups performed |
| `Situps` | sit-ups performed |
| `Jumps` | jumping jacks performed |

Only 20 rows — small enough to check your answers by eye.

> **Counting warning for this whole section.** "The 16th value" means the 16th one you would count starting at 1 — but **Python indexes from 0**, so the 16th row has index `15`. Each problem below states the expected answer, so you can tell at once if you are off by one.

**Run the setup cell below before answering.**

In [ ]:
# Load the dataset
linnerud = datasets.load_linnerud()

# Create the DataFrame
linnerud_df = pd.DataFrame(data=linnerud.data, columns=linnerud.feature_names)

linnerud_df

    Chins  Situps  Jumps
0     5.0   162.0   60.0
1     2.0   110.0   60.0
2    12.0   101.0  101.0
3    12.0   105.0   37.0
4    13.0   155.0   58.0
5     4.0   101.0   42.0
6     8.0   101.0   38.0
7     6.0   125.0   40.0
8    15.0   200.0   40.0
9    17.0   251.0  250.0
10   17.0   120.0   38.0
11   13.0   210.0  115.0
12   14.0   215.0  105.0
13    1.0    50.0   50.0
14    6.0    70.0   31.0
15   12.0   210.0  120.0
16    4.0    60.0   25.0
17   11.0   230.0   80.0
18   15.0   225.0   73.0
19    2.0   110.0   43.0

<!-- @anchor:P6.1 type=code -->
#### Problem 6.1  `[code]`

Print the **16th value of `Chins`** — a single number.

**Expected output**
```
12.0
```

*The 16th row has index `15`. Two ways work: take the whole 16th row and then pick `Chins` off it, or select the row and the column together. Either is fine.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P6.1
# YOUR CODE HERE  (do not delete this cell)
print(linnerud_df.iloc[15]['Chins'])

12.0

<!-- @anchor:P6.2 type=code -->
#### Problem 6.2  `[code]`

Print the **9th value of `Situps`**.

**Expected output**
```
200.0
```

*Same move as 6.1. The 9th row has index `8`.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P6.2
# YOUR CODE HERE  (do not delete this cell)

print(linnerud_df.iloc[8]['Situps'])

200.0

<!-- @anchor:P6.3 type=code -->
#### Problem 6.3  `[code]`

Display the **entire 4th row**.

**Expected output**
```
Chins      12.0
Situps    105.0
Jumps      37.0
Name: 3, dtype: float64
```

*`Name: 3` confirms you got the right row — the 4th row has index `3`.*

In [ ]:
# @answer:P6.3
# YOUR CODE HERE  (do not delete this cell)

linnerud_df.iloc[3]

Chins      12.0
Situps    105.0
Jumps      37.0
Name: 3, dtype: float64

<!-- @anchor:P6.4 type=code -->
#### Problem 6.4  `[code]`

Display the **whole `Jumps` column** (all 20 values).

**Expected result:** all 20 values, index `0` to `19`, ending with the line `Name: Jumps, dtype: float64`. The first three are `60.0`, `60.0`, `101.0`; the largest is `250.0` at index `9`.

*No `.iloc` needed — selecting a column by name is enough.*

In [ ]:
# @answer:P6.4
# YOUR CODE HERE  (do not delete this cell)

linnerud_df['Jumps']

0      60.0
1      60.0
2     101.0
3      37.0
4      58.0
5      42.0
6      38.0
7      40.0
8      40.0
9     250.0
10     38.0
11    115.0
12    105.0
13     50.0
14     31.0
15    120.0
16     25.0
17     80.0
18     73.0
19     43.0
Name: Jumps, dtype: float64

<!-- @anchor:P6.5 type=code -->
#### Problem 6.5  `[code]`

Display the **12th through 16th rows** — that is **5 rows**.

**Expected output**
```
    Chins  Situps  Jumps
11   13.0   210.0  115.0
12   14.0   215.0  105.0
13    1.0    50.0   50.0
14    6.0    70.0   31.0
15   12.0   210.0  120.0
```

**Read the index carefully: `11` to `15`.** The 12th row is index 11, the 16th is index 15. With `.iloc[a:b]` the END is EXCLUDED, so `b` must be one past the last row you want.

*Count your output: if you got 4 rows, you are the classic off-by-one.*

In [ ]:
# @answer:P6.5
# YOUR CODE HERE  (do not delete this cell)

linnerud_df.iloc[11:16]

    Chins  Situps  Jumps
11   13.0   210.0  115.0
12   14.0   215.0  105.0
13    1.0    50.0   50.0
14    6.0    70.0   31.0
15   12.0   210.0  120.0

---
#### Try Problems 6.6 – 6.12 on your own.
---

<!-- @anchor:P6.6 type=code -->
#### Problem 6.6  `[code]`

Display the rows with **index labels `10` through `15`, inclusive** — that is **6 rows**.

**Expected output**
```
    Chins  Situps  Jumps
10   17.0   120.0   38.0
11   13.0   210.0  115.0
12   14.0   215.0  105.0
13    1.0    50.0   50.0
14    6.0    70.0   31.0
15   12.0   210.0  120.0
```

*Note this asks for index LABELS, not "the 10th to 15th rows". `.loc[10:15]` includes both ends; `.iloc[10:16]` gets the same rows by position. Either is correct.*

In [ ]:
# @answer:P6.6
# YOUR CODE HERE  (do not delete this cell)

linnerud_df.iloc[10:16]

    Chins  Situps  Jumps
10   17.0   120.0   38.0
11   13.0   210.0  115.0
12   14.0   215.0  105.0
13    1.0    50.0   50.0
14    6.0    70.0   31.0
15   12.0   210.0  120.0

<!-- @anchor:P6.7 type=code -->
#### Problem 6.7  `[code]`

Display **only the `Situps` and `Jumps` columns** (all 20 rows, `Chins` left out).

**Expected result:** a **20 × 2** table — just those two columns, in that order. The first row is `Situps` `162.0`, `Jumps` `60.0`.

*Hint: to select several columns you pass a LIST of names — so there are two sets of brackets.*

In [ ]:
# @answer:P6.7
# YOUR CODE HERE  (do not delete this cell)

linnerud_df[['Situps', 'Jumps']]

    Situps  Jumps
0    162.0   60.0
1    110.0   60.0
2    101.0  101.0
3    105.0   37.0
4    155.0   58.0
5    101.0   42.0
6    101.0   38.0
7    125.0   40.0
8    200.0   40.0
9    251.0  250.0
10   120.0   38.0
11   210.0  115.0
12   215.0  105.0
13    50.0   50.0
14    70.0   31.0
15   210.0  120.0
16    60.0   25.0
17   230.0   80.0
18   225.0   73.0
19   110.0   43.0

<!-- @anchor:P6.8 type=code -->
#### Problem 6.8  `[code]`

Display only the rows where **`Situps` is greater than 100**.

**Expected result:** **17 of the 20 rows** — everyone except index `13`, `14`, and `16`. The index keeps its original labels; pandas filters rows, it does not renumber them.

*Hint: boolean indexing (Lab 1, Section 2.4) — build the condition inside the brackets.*

In [ ]:
# @answer:P6.8
# YOUR CODE HERE  (do not delete this cell)

linnerud_df[linnerud_df['Situps'] > 100]

    Chins  Situps  Jumps
0     5.0   162.0   60.0
1     2.0   110.0   60.0
2    12.0   101.0  101.0
3    12.0   105.0   37.0
4    13.0   155.0   58.0
5     4.0   101.0   42.0
6     8.0   101.0   38.0
7     6.0   125.0   40.0
8    15.0   200.0   40.0
9    17.0   251.0  250.0
10   17.0   120.0   38.0
11   13.0   210.0  115.0
12   14.0   215.0  105.0
15   12.0   210.0  120.0
17   11.0   230.0   80.0
18   15.0   225.0   73.0
19    2.0   110.0   43.0

<!-- @anchor:P6.9 type=code -->
#### Problem 6.9  `[code]`

Print the value in the **third row, second column**.

**Expected output**
```
101.0
```

*Third row = index `2`; second column = position `1` (`Situps`). `.iloc[]` takes both at once: `.iloc[row, column]`.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P6.9
# YOUR CODE HERE  (do not delete this cell)

print(linnerud_df.iloc[2,1])

101.0

<!-- @anchor:P6.10 type=code -->
#### Problem 6.10  `[code]`

Print the **17th value of `Jumps`**.

**Expected output**
```
25.0
```

*Same move as 6.1 / 6.2. The 17th row has index `16`.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P6.10
# YOUR CODE HERE  (do not delete this cell)

print(linnerud_df.iloc[16]['Jumps'])

25.0

<!-- @anchor:P6.11 type=code -->
#### Problem 6.11  `[code]`

Display only the rows where **`Chins` is greater than 6**.

**Expected result:** **11 rows** — index `2`, `3`, `4`, `6`, `8`, `9`, `10`, `11`, `12`, `15`, `17`, `18`. The first row shown is index `2` (`Chins` 12.0).

*Same move as 6.8, different column.*

In [ ]:
# @answer:P6.11
# YOUR CODE HERE  (do not delete this cell)

linnerud_df[linnerud_df['Chins'] > 6]

    Chins  Situps  Jumps
2    12.0   101.0  101.0
3    12.0   105.0   37.0
4    13.0   155.0   58.0
6     8.0   101.0   38.0
8    15.0   200.0   40.0
9    17.0   251.0  250.0
10   17.0   120.0   38.0
11   13.0   210.0  115.0
12   14.0   215.0  105.0
15   12.0   210.0  120.0
17   11.0   230.0   80.0
18   15.0   225.0   73.0

<!-- @anchor:P6.12 type=code -->
#### Problem 6.12  `[code]`

Display the **6th through 10th rows** (5 rows), showing **only the `Chins` and `Jumps` columns**.

**Expected output**
```
   Chins  Jumps
5    4.0   42.0
6    8.0   38.0
7    6.0   40.0
8   15.0   40.0
9   17.0  250.0
```

*This combines 6.6 (a row range) with 6.7 (a column list). `.loc[<rows>, <column list>]` does both in one call — remember `.loc` INCLUDES the end label.*

In [ ]:
# @answer:P6.12
# YOUR CODE HERE  (do not delete this cell)

linnerud_df.loc[5:9, ['Chins', 'Jumps']]

   Chins  Jumps
5    4.0   42.0
6    8.0   38.0
7    6.0   40.0
8   15.0   40.0
9   17.0  250.0

In [ ]:
print(linnerud_df[['Jumps']])
print(linnerud_df['Jumps'])

    Jumps
0    60.0
1    60.0
2   101.0
3    37.0
4    58.0
5    42.0
6    38.0
7    40.0
8    40.0
9   250.0
10   38.0
11  115.0
12  105.0
13   50.0
14   31.0
15  120.0
16   25.0
17   80.0
18   73.0
19   43.0
0      60.0
1      60.0
2     101.0
3      37.0
4      58.0
5      42.0
6      38.0
7      40.0
8      40.0
9     250.0
10     38.0
11    115.0
12    105.0
13     50.0
14     31.0
15    120.0
16     25.0
17     80.0
18     73.0
19     43.0
Name: Jumps, dtype: float64

<!-- @anchor:S6R type=explain -->
### Reflection — Section 6: Working with Rows and Columns
In a sentence or two — **what can you now do that you could not before?**

- `.iloc[a:b]` excludes `b`, but `.loc[a:b]` includes it. Did that catch you out — and on which problem?
- What is the difference between `df['Jumps']` and `df[['Jumps']]`? Try both if you are not sure.

<!-- @answer:S6R -->
*(write your takeaway here — do not delete this cell)* --- I now know how to grab certain columns at specific indexes. I thought i knew how to before, however after starting this section I came to the conclution I did not. BUT I DO NOW! Yes, the difference between iloc and loc through me off at first but I think i understand it now its not too difficult of a change where it will be hard to remember. I am not sure if I am missing something but I cant tell the differene between the two calls. They both are getting all rows for the Jumps column. One just has an Extra set of square brackets around the 'Jumps'

> **Save and pin a revision now** — `File` → `Save and pin revision` — and name it **`Section 6`**. Do not delete the cells above.

## Section 7 — Exploring the Mean, Median and Sum

**Goal of this section:** summarize a whole column down to one number.

| Method | Gives |
|---|---|
| `.mean()` | the average |
| `.median()` | the middle value when sorted |
| `.sum()` | the total |

All problems use `linnerud_df` from Section 6.

<!-- @anchor:P7.1 type=code -->
#### Problem 7.1  `[code]`

Print the **mean of `Jumps`**.

**Expected output**
```
70.3
```

*Select the column, then call the method on it.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P7.1
# YOUR CODE HERE  (do not delete this cell)

print(linnerud_df['Jumps'].mean())

70.3

<!-- @anchor:P7.2 type=code -->
#### Problem 7.2  `[code]`

Print the **median of `Jumps`**.

**Expected output**
```
54.0
```

*The mean (70.3) is much higher than the median (54.0) — one man did 250 jumping jacks and drags the average up. The median ignores him. That gap is exactly why you report both.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P7.2
# YOUR CODE HERE  (do not delete this cell)

print(linnerud_df['Jumps'].median())

54.0

<!-- @anchor:P7.3 type=code -->
#### Problem 7.3  `[code]`

Print the **sum of `Jumps`** — the total jumping jacks by all 20 men.

**Expected output**
```
1406.0
```

*Check it: 1406 ÷ 20 = 70.3, the mean from 7.1.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P7.3
# YOUR CODE HERE  (do not delete this cell)


print(linnerud_df['Jumps'].sum())

1406.0

---
#### Try Problems 7.4 – 7.6 on your own.
---

<!-- @anchor:P7.4 type=code -->
#### Problem 7.4  `[code]`

Print the **mean of `Situps`**.

**Expected output**
```
145.55
```

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P7.4
# YOUR CODE HERE  (do not delete this cell)


print(linnerud_df['Situps'].mean())

145.55

<!-- @anchor:P7.5 type=code -->
#### Problem 7.5  `[code]`

Print the **median of `Situps`**.

**Expected output**
```
122.5
```

*Again the mean sits above the median — but the gap is much smaller than it was for `Jumps`. Why? Look back at the data.*

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P7.5
# YOUR CODE HERE  (do not delete this cell)


print(linnerud_df['Situps'].median())

122.5

<!-- @anchor:P7.6 type=code -->
#### Problem 7.6  `[code]`

Print the **sum of `Situps`**.

**Expected output**
```
2911.0
```

*Wrap it in `print()`. Without it the cell shows `np.float64(...)` around the number — that is the same value, just numpy's way of displaying a lone number.*

In [ ]:
# @answer:P7.6
# YOUR CODE HERE  (do not delete this cell)

print(linnerud_df['Situps'].sum())

2911.0

<!-- @anchor:S7R type=explain -->
### Reflection — Section 7: Exploring the Mean, Median and Sum
In a sentence or two — **what can you now do that you could not before?**

- For `Jumps` the mean was 70.3 but the median 54.0. Explain the gap, and say which number you would report to the fitness center.
- Across this whole notebook you used three different datasets. What did you have to change to move from one to the next — and what stayed the same?

<!-- @answer:S7R -->
*(write your takeaway here — do not delete this cell)* --- This section was very havally focused on how to find the mean,median, and sum of different column numbers ( such as jumps and situps ). It also showed me good practice for why I should use mean and median when reporting the average. The large gap between jumps mean and median has to do with one person doing such a large number of jumping jacks compared to the others it dragged the mean up by 15. I would report the 54 jumping jacks since most people do that number rather than just the one guy who can do a lot. For the most part, the syntax stayed exactally the same and the only things i ended up changing were the actuall names of the columns! so once i have the syntax memorized I could do this kinf of insight with any data set! --

> **Save and pin a revision now** — `File` → `Save and pin revision` — and name it **`Section 7`**. Do not delete the cells above.